// Package provisioning — 확정 계획에서 프로비저닝 산출물(Ansible 플레이북·롤백·레코드)을 생성한다(프로비저닝 설계 §5).
// 자체 원격 실행 엔진을 만들지 않는다(§4.4) — 사용자의 기존 substrate(Ansible)가 실행하도록
// 플레이북을 "생성"만 한다. 대상은 스코프 마스터 게이트 통과 노드에 한정(§1.4).
package provisioning

import (
	"fmt"
	"strings"
)

// GeneratePlaybook — T2(substrate-반자동): collector 바이너리를 대상 노드에 복사·실행하고
// 결과를 회수하는 Ansible 플레이북 YAML을 생성한다. 실행 주체는 사용자(§2.3 T2).
//
// nodes는 이미 스코프 마스터로 게이트된 것이어야 한다(§1.4는 코어 책임).
func GeneratePlaybook(nodes []string, collectorBin, remotePath string) string {
	var b strings.Builder
	b.WriteString("# generated by pqcota: T2 deployment playbook (run by your own Ansible)\n")
	b.WriteString("# not a push engine of our own — it reuses a proven substrate (§4.4). Targets = nodes past the scope gate (§1.4).\n")
	b.WriteString("- name: pqcota openssl-collector deploy and collect\n")
	b.WriteString("  hosts:\n")
	for _, n := range nodes {
		fmt.Fprintf(&b, "    - %s\n", n)
	}
	b.WriteString("  become: true   # needed to read other processes under /proc (CAP_SYS_PTRACE/root)\n")
	b.WriteString("  tasks:\n")
	fmt.Fprintf(&b, "    - name: stage the collector binary\n")
	fmt.Fprintf(&b, "      ansible.builtin.copy:\n")
	fmt.Fprintf(&b, "        src: %s\n", collectorBin)
	fmt.Fprintf(&b, "        dest: %s\n", remotePath)
	fmt.Fprintf(&b, "        mode: '0755'\n")
	fmt.Fprintf(&b, "    - name: run the collector (read-only collection)\n")
	fmt.Fprintf(&b, "      ansible.builtin.command: %s\n", remotePath)
	fmt.Fprintf(&b, "      register: pqcota_out\n")
	fmt.Fprintf(&b, "    - name: fetch the result (signed report)\n")
	fmt.Fprintf(&b, "      ansible.builtin.debug:\n")
	fmt.Fprintf(&b, "        var: pqcota_out.stdout\n")
	return b.String()
}
