package provisioning

import (
	"fmt"
	"strings"

	provisioningv1 "github.com/randyinthedev-hash/pqcota-common/gen/pqcota/provisioning/v1"
)

// renderJCA — JCA/JCE remediation taxonomy(프로비저닝 설계 §4.2) → java.security 조각.
//   - CONFIG_ONLY (JDK 네이티브 PQC): namedGroups·순서 config만. provider 무등록.
//   - PROVIDER_INJECT (provider JAR) : provider 클래스 등록 + JAR 배치 + namedGroups.
//   - 그 외(앱 reconfig·JDK 업그레이드·재빌드·폐기): config로 안 되는 조치 → 주석 블록.
func renderJCA(a *provisioningv1.RemediationAction) string {
	group := hybridGroup(a.GetTargetAlgorithm())
	switch a.GetKind() {
	case provisioningv1.RemediationKind_REMEDIATION_KIND_CONFIG_ONLY:
		return jcaConfigOnly(group, a.GetTargetAlgorithm())
	case provisioningv1.RemediationKind_REMEDIATION_KIND_PROVIDER_INJECT:
		return jcaProviderInject(group, a.GetTargetAlgorithm(), a.GetProviderChoice(), a.GetProviderClass())
	default:
		return jcaNonConfig(a)
	}
}

// providerClass — provider 라우팅(프로비저닝 설계 §4.2) → java.security 등록 클래스명.
//
// 계획이 provider_class를 명시했으면 그대로 쓴다 — 커스텀 provider가 계획만으로 완결되는 경로다.
// 명시가 없으면 알려진 이름(BC/BCFIPS)만 확정하고, 그 외는 placeholder로 두고 provider 문서
// 확인을 명시한다(추측해서 채우지 않는다).
//
// ★ BC의 정답은 **버전에 달렸다**(실측): 1.80·1.81의 BouncyCastleProvider에는 ML-KEM 서비스가
// 17개 있으나 1.78.1에는 **0개**이고 Kyber가 BouncyCastlePQCProvider에 따로 있다. 기본값은 현재
// 통용되는 1.80+ 기준으로 두되, 그 전제를 조각에 적어 둔다 — 계획이 JAR 버전을 알려주지 않으므로
// 도구가 대신 안다고 할 수 없다(§2.5).
func providerClass(choice, explicit string) (class string, exact bool) {
	if explicit != "" {
		return explicit, true
	}
	switch choice {
	case "BC":
		return "org.bouncycastle.jce.provider.BouncyCastleProvider", true
	case "BCFIPS", "BC-FJA":
		return "org.bouncycastle.jcajce.provider.BouncyCastleFipsProvider", true
	default:
		if choice == "" {
			choice = "BC"
			return "org.bouncycastle.jce.provider.BouncyCastleProvider", true
		}
		return fmt.Sprintf("<%s: check the provider docs for the exact class name>", choice), false
	}
}

// namedGroupsLine — JDK TLS 협상 그룹(PQC 우선, 고전 폴백으로 하위호환).
func namedGroupsLine(group string) string {
	if group == "" {
		return "# jdk.tls.namedGroups: the target is not a hybrid KEM group (signature or unknown) — set this by hand\n"
	}
	return fmt.Sprintf("jdk.tls.namedGroups=%s,x25519\n", group)
}

func jcaConfigOnly(group, target string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by pqcota: JDK-native PQC, config-only — %s\n", target)
	b.WriteString("# no provider registered. Only natively supported groups join the negotiation. Rollback = delete this fragment.\n")
	b.WriteString(namedGroupsLine(group))
	return b.String()
}

func jcaProviderInject(group, target, choice, explicitClass string) string {
	class, exact := providerClass(choice, explicitClass)
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by pqcota: JCA provider injection — %s (provider=%s)\n", target, choice)
	b.WriteString("# stage the JAR, then register it in java.security. Augments providers without redeploying. Rollback = delete the registration line.\n")
	if !exact {
		b.WriteString("# ⚠ the class name below is a placeholder — replace it with the exact class from your provider build, or\n")
		b.WriteString("#   put the FQCN in the plan's provider_class and it is filled in automatically.\n")
	}
	// 계획이 클래스를 명시하지 않아 BC 기본값을 쓴 경우에만 — 명시했다면 그것은 저자의 결정이다.
	if explicitClass == "" && (choice == "BC" || choice == "") {
		b.WriteString("# ⚠ assumes BouncyCastle **1.80+**. On 1.78.x and older, BouncyCastleProvider has no KEM and\n")
		b.WriteString("#   Kyber lives separately in org.bouncycastle.pqc.jcajce.provider.BouncyCastlePQCProvider.\n")
		b.WriteString("#   if the JAR you stage is of that generation, name that class in the plan's provider_class.\n")
	}
	// JAR은 플레이북이 여기 놓는다. JVM이 찾게 하려면 클래스패스에 얹어야 하는데, 그 방법이
	// JDK 세대마다 다르다 — 확장 메커니즘(lib/ext)은 JDK 9에서 제거됐다.
	fmt.Fprintf(&b, "# JAR staged at: %s (the playbook puts it there)\n", ModulePath(choice, true))
	b.WriteString("#   JDK 8  : put it in $JAVA_HOME/jre/lib/ext, or on the app classpath\n")
	b.WriteString("#   JDK 9+ : there is no lib/ext — put it on the classpath or --module-path\n")
	// 우선순위 N: 디스패치 체인 진입 보장 위해 상위(2)에 둔다. 전역 변경이라 blast radius가 있다(프로비저닝 설계 §4.2).
	//
	// ★ 이 줄은 **끼워 넣지 않고 그 자리를 차지한다**(실측: JDK 21에서 provider.2를 이 값으로 두면
	// 원래 2번이던 SunRsaSign이 목록에서 사라진다 — 12개가 12개 그대로이고 이름만 바뀐다). 삽입처럼
	// 읽히게 적으면 거짓말이 되므로 조각에 그렇게 적는다. 밀어내지 않고 넣으려면 뒤 번호를 전부
	// 한 칸씩 미뤄야 하는데, 그러려면 그 노드의 java.security 원본을 알아야 한다 — 도구는 모른다(§2.5).
	fmt.Fprintf(&b, "security.provider.2=%s\n", class)
	b.WriteString("# ↑ priority 2 — so PQC algorithms are dispatched first (providers are consulted in order, so the earlier one serves an algorithm first).\n")
	b.WriteString("# ⚠ this line **takes over slot 2** (it does not insert). Whatever was provider 2\n")
	b.WriteString("#   drops off the list — on JDK defaults that is usually SunRsaSign, which moves RSA services\n")
	b.WriteString("#   over to this provider's implementation. To avoid displacing it, renumber the entries below\n")
	b.WriteString("#   by one in the target node's java.security first, then add this line.\n")
	b.WriteString(namedGroupsLine(group))
	return b.String()
}

// jcaNonConfig — java.security 조각으로 해결 불가한 조치(프로비저닝 설계 §4.2 "레거시를 건드리나").
func jcaNonConfig(a *provisioningv1.RemediationAction) string {
	var reason string
	switch a.GetKind() {
	case provisioningv1.RemediationKind_REMEDIATION_KIND_APP_RECONFIG:
		reason = "the app names a provider explicitly via getInstance(...,\"BC\") or pins groups — the app code or its config must change."
	case provisioningv1.RemediationKind_REMEDIATION_KIND_JDK_UPGRADE:
		reason = "end-of-life JDK — upgrade the JDK or front it with a proxy. Touching legacy: required."
	case provisioningv1.RemediationKind_REMEDIATION_KIND_REBUILD:
		reason = "shaded crypto — needs a CI rebuild. Touching legacy: required."
	case provisioningv1.RemediationKind_REMEDIATION_KIND_DECOMMISSION:
		reason = "end of life, low value — decommission or accept the risk."
	default:
		reason = "a remediation that cannot be injected through config."
	}
	return fmt.Sprintf("# pqcota: JCA non-config remediation (%s)\n# %s\n# → no java.security fragment is generated for this. See the manual step in the plan.\n",
		a.GetKind(), reason)
}
