package provisioning

import (
	"fmt"
	"strings"

	provisioningv1 "github.com/randyinthedev-hash/pqcota-common/gen/pqcota/provisioning/v1"
)

// renderOpenSSL — OpenSSL remediation taxonomy(프로비저닝 설계 §4.1) → openssl.cnf 조각.
//   - CONFIG_ONLY (3.5+ 네이티브)   : 하이브리드 그룹 활성화만. 레거시·provider를 건드리지 않는다.
//   - PROVIDER_INJECT (3.0–3.4)     : provider 모듈 로드 + 활성화 + 그룹. cnf 롤백 가역.
//   - 그 외(포크교체·프록시·재빌드·폐기): config로 안 되는 조치 → 주석 블록으로 정직하게.
func renderOpenSSL(a *provisioningv1.RemediationAction) string {
	group := hybridGroup(a.GetTargetAlgorithm())
	switch a.GetKind() {
	case provisioningv1.RemediationKind_REMEDIATION_KIND_CONFIG_ONLY:
		return opensslConfigOnly(group, a.GetTargetAlgorithm())
	case provisioningv1.RemediationKind_REMEDIATION_KIND_PROVIDER_INJECT:
		return opensslProviderInject(group, a.GetTargetAlgorithm(), a.GetProviderChoice())
	default:
		return opensslNonConfig(a)
	}
}

// initDirective — 섹션보다 먼저 와야 하는 최상위 지시자. 이 한 줄이 없으면 OpenSSL은
// [openssl_init]을 **아예 보지 않는다** — 조각을 OPENSSL_CONF로 직접 가리키면(활성화 지점이
// 그런 환경이면 흔하다) 배치도 되고 게이트도 통과하는데 능력은 그대로인 상태가 된다.
// 실제로 그랬다: 실물 oqsprovider를 배치·활성화했는데 `openssl list -providers`에 안 떴다.
// 조각을 시스템 cnf에서 .include 하는 환경에서는 이 줄이 중복되지만, 같은 값의 재대입이라
// 무해하다(3.0.13에서 확인). 두 활성화 경로 중 하나만 되는 것보다 낫다.
const initDirective = "openssl_conf = openssl_init\n\n"

// groupsLine — 하이브리드 그룹 + 고전 폴백(하위호환 접속 유지, 프로비저닝 설계 §4.1 검증 매트릭스).
func groupsLine(group string) string {
	if group == "" {
		return "# Groups: the target is not a hybrid KEM group (signature or unknown) — set this by hand\n"
	}
	return fmt.Sprintf("Groups = %s:x25519\n", group) // PQC 우선, 고전 폴백
}

func opensslConfigOnly(group, target string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by pqcota: OpenSSL 3.5+ config-only — enables the %s hybrid\n", target)
	b.WriteString("# legacy and providers untouched. Rollback = delete this fragment.\n")
	b.WriteString(initDirective)
	b.WriteString("[openssl_init]\n")
	b.WriteString("ssl_conf = ssl_sect\n\n")
	b.WriteString("[ssl_sect]\n")
	b.WriteString("system_default = system_default_sect\n\n")
	b.WriteString("[system_default_sect]\n")
	b.WriteString(groupsLine(group))
	return b.String()
}

func opensslProviderInject(group, target, provider string) string {
	if provider == "" {
		provider = "oqsprovider" // 3.0–3.4 표준 PQC provider 기본값(프로비저닝 설계 §4.2 특수 케이스는 내부 provider)
	}
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by pqcota: OpenSSL 3.0-3.4 provider injection — %s (provider=%s)\n", target, provider)
	b.WriteString("# the version stays; only the algorithm capability is replaced by staging a provider. Rollback = one line in the cnf.\n")
	b.WriteString(initDirective)
	b.WriteString("[openssl_init]\n")
	b.WriteString("providers = provider_sect\n")
	b.WriteString("ssl_conf = ssl_sect\n\n")
	b.WriteString("[provider_sect]\n")
	b.WriteString("default = default_sect\n")
	fmt.Fprintf(&b, "%s = %s_sect\n\n", provider, provider)
	b.WriteString("[default_sect]\n")
	b.WriteString("activate = 1\n\n")
	fmt.Fprintf(&b, "[%s_sect]\n", provider)
	b.WriteString("activate = 1\n")
	// 절대 경로 — 상대명이면 OpenSSL이 모듈 디렉터리(OPENSSL_MODULES/MODULESDIR)에서 찾는데
	// 플레이북이 배치하는 곳은 거기가 아니다. 배치 위치를 아는 쪽이 경로를 적는다(paths.go).
	fmt.Fprintf(&b, "module = %s\n\n", ModulePath(provider, false))
	b.WriteString("[ssl_sect]\n")
	b.WriteString("system_default = system_default_sect\n\n")
	b.WriteString("[system_default_sect]\n")
	b.WriteString(groupsLine(group))
	return b.String()
}

// opensslNonConfig — config 주입으로 해결 불가한 조치. 무엇을·왜 수동인지 명시(프로비저닝 설계 §4.1 "레거시를 건드리나").
func opensslNonConfig(a *provisioningv1.RemediationAction) string {
	var reason string
	switch a.GetKind() {
	case provisioningv1.RemediationKind_REMEDIATION_KIND_FORK_REPLACE:
		reason = "needs a fork or version replacement (1.1.1, 1.0.2 — no provider API). Touching legacy: required."
	case provisioningv1.RemediationKind_REMEDIATION_KIND_PROXY_FRONT:
		reason = "terminate PQC in front via a proxy. The leave-legacy-alone option — deploy a separate proxy."
	case provisioningv1.RemediationKind_REMEDIATION_KIND_REBUILD:
		reason = "statically or vendored linked — needs a CI rebuild. Touching legacy: required."
	case provisioningv1.RemediationKind_REMEDIATION_KIND_DECOMMISSION:
		reason = "end of life, low value — decommission or accept the risk."
	default:
		reason = "a remediation that cannot be injected through config."
	}
	return fmt.Sprintf("# pqcota: OpenSSL non-config remediation (%s)\n# %s\n# → no openssl.cnf fragment is generated for this. See the manual step in the plan.\n",
		a.GetKind(), reason)
}
