// SPDX-FileCopyrightText: 2026 randyinthedev
// SPDX-License-Identifier: Apache-2.0

package provisioning

import (
	"fmt"
	"strings"

	commonv1 "github.com/randyinthedev-hash/pqcota-common/gen/pqcota/common/v1"
	provisioningv1 "github.com/randyinthedev-hash/pqcota-common/gen/pqcota/provisioning/v1"
)

// GenerateRollbackPlaybook — GenerateProvisioningPlaybook의 역방향(프로비저닝 설계 §6A). forward가 스테이지한
// provider 모듈과 배치한 config 조각을 **제거**해 before 상태로 되돌리는 Ansible 플레이북을 생성한다.
//
// forward는 원본(기존 모듈·config)을 *덮어쓰지 않고 파일을 추가*하므로(프로비저닝 설계 §6A 원자적 배치), 그 추가분을
// 지우면 원본이 그대로 복원된다 — before 원문을 따로 재생성할 필요가 없다.
//
// L3면 **forward의 정확한 역순**으로 되돌린다: pre → deactivate → 파일 제거 → restart.
// activate가 바꾼 것(include·symlink 등)은 그것을 만든 사람만 되돌릴 수 있으니 deactivate 훅을 쓴다.
// level은 forward와 같은 뜻이다 — 계획이 말하지 않은 조치의 기본값(LevelFor). 되돌림이 대칭이려면
// 놓을 때와 지울 때가 **같은 수준으로** 갈려야 한다.
func GenerateRollbackPlaybook(plan *provisioningv1.FinalizedPlan, level provisioningv1.DeployAutomationLevel) string {
	var b strings.Builder
	b.WriteString("# generated by pqcota: rollback playbook — undo it with `ansible-playbook`.\n")
	fmt.Fprintf(&b, "# default level: %s — applied only to actions whose automation_level is unset.\n", levelName(level))
	if anyAt(plan.GetActions(), level, activatesAt) {
		b.WriteString("# L3 actions in reverse: deactivate → undo activation → remove staged files → restart (originals untouched).\n")
	} else {
		b.WriteString("# in reverse: remove the files the forward run staged (originals untouched).\n")
	}
	// ★ 이 플레이북은 **이번 계획이 놓은 고정 경로의 산출물을 지운다.** 원본 설정을 덮은 적이
	// 없으므로 원본은 그대로 남지만, 같은 provider 이름·같은 config 경로로 **두 번째 배포**를
	// 했다면 첫 배포의 pqcota 산출물은 이미 덮여 있다. 그때 이것을 돌리면 이전 판으로 돌아가는
	// 것이 아니라 파일이 사라진다. 직전 pqcota 배포판까지 복원하는 버전 롤백이 아니다.
	b.WriteString("# NOTE: this removes what THIS plan stages. It is not a version rollback — if a later run\n")
	b.WriteString("#   overwrote an earlier pqcota artifact at the same path, undoing it deletes the file\n")
	b.WriteString("#   rather than restoring the earlier one. Originals outside these paths are untouched.\n")

	byNode := map[string][]*provisioningv1.RemediationAction{}
	var order []string
	for _, a := range plan.GetActions() {
		n := a.GetTargetNodeId()
		if _, ok := byNode[n]; !ok {
			order = append(order, n)
		}
		byNode[n] = append(byNode[n], a)
	}

	for _, node := range order {
		fmt.Fprintf(&b, "\n- name: %s\n", yamlScalar("pqcota rollback — "+node))
		fmt.Fprintf(&b, "  hosts: [%s]\n", yamlScalar(node))
		b.WriteString("  become: true\n  tasks:\n")
		// L3 역순: 먼저 내리고(pre) 활성화를 되돌린 뒤(deactivate) 파일을 지운다.
		// forward와 같은 이유로 단계별로 모아 낸다 — 조치별 재시작은 서비스를 여러 번 흔든다.
		l3 := actionsAt(byNode[node], level, activatesAt)
		if len(l3) > 0 {
			writeHooks(&b, "① deactivate (pre)", hookCmds(l3, (*provisioningv1.ActivationHooks).GetPre))
			writeHooks(&b, "② undo activation", hookCmds(l3, (*provisioningv1.ActivationHooks).GetDeactivate))
		}
		// forward와 **같은 규칙**으로 계산한다 — 놓은 것을 그대로 지운다.
		dests := ConfigDests(actionsAt(byNode[node], level, installsAt))
		removed := map[string]bool{}
		for _, a := range byNode[node] {
			d := dests[a.GetId()]
			if d != "" && removed[d] {
				d = ""
			} else if d != "" {
				removed[d] = true
			}
			writeRollbackTasks(&b, a, d)
		}
		// 마지막에 재시작해 원래 설정으로 다시 로드시킨다.
		if len(l3) > 0 {
			writeHooks(&b, "④ restart", hookCmds(l3, (*provisioningv1.ActivationHooks).GetRestart))
		}
	}
	return b.String()
}

func writeRollbackTasks(b *strings.Builder, a *provisioningv1.RemediationAction, cfgDest string) {
	kind := a.GetKind()
	inject := kind == provisioningv1.RemediationKind_REMEDIATION_KIND_PROVIDER_INJECT
	cfgOnly := kind == provisioningv1.RemediationKind_REMEDIATION_KIND_CONFIG_ONLY
	if !inject && !cfgOnly {
		fmt.Fprintf(b, "    # action %s (%s): it was never delivered through config, so the rollback is manual too (touching legacy)\n", a.GetId(), kind)
		return
	}

	jca := a.GetCryptoRuntime() == commonv1.CryptoRuntime_CRYPTO_RUNTIME_JCA

	// L2에서 배치한 config 조각 제거(L1 stage-only면 config를 배치 안 했으니 스킵).
	if cfgDest != "" {
		fmt.Fprintf(b, "    - name: %s\n", yamlScalar("remove the config fragment ("+cfgDest+")"))
		fmt.Fprintf(b, "      ansible.builtin.file: { path: %s, state: absent }\n", yamlScalar(cfgDest))
	}

	if inject { // 스테이지한 provider 모듈 제거 — forward가 놓은 그 경로(paths.go 공유)
		prov := a.GetProviderChoice()
		if prov == "" {
			prov = "provider"
		}
		fmt.Fprintf(b, "    - name: %s\n", yamlScalar("remove the provider module ("+prov+")"))
		fmt.Fprintf(b, "      ansible.builtin.file: { path: %s, state: absent }\n", yamlScalar(ModulePath(prov, jca)))
	}
}
